---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka
  namespace: stellar
spec:
  releaseName: kafka
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: kafka
    version: 12.2.1
  values:
    usePassword: false
    replicaCount: 3
    numPartitions: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 100m

