---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka
spec:
  releaseName: kafka
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: kafka
    version: 12.2.1
  values:
    usePassword: false
    replicaCount: 2
    numPartitions: 1
