---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: stellar
spec:
  releaseName: redis
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 12.2.1
  values:
    usePassword: false
    cluster:
      slaveCount: 0
    master:
      extraFlags:
        - "--maxmemory-policy allkeys-lfu"
      resources:
        requests:
          memory: 0.1Gi
          cpu: "0.1"
    slave:
      resources:
        requests:
          memory: 0.1Gi
          cpu: "0.1"